# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
minecraft_version=1.21.10
minecraft_version_out=1.21.10
yarn_mappings=1.21.10+build.3
loader_version=0.18.0
# Mod Properties
mod_version=1.0.0-beta.4
maven_group=gc.mc
archives_base_name=GlowTools-fabric-mc1.21.10
# Dependencies
fabric_version=0.136.0+1.21.10
malilib_version=0.26.8
tweakeroo_version=0.26.5
mod_menu_version = 16.0.0
