# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.2
minecraft_version_out=26.2
loader_version=0.18.6
# Mod Properties
mod_version=1.0.0-beta.6
maven_group=gc.mc
archives_base_name=GlowTools-fabric-mc26.2
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.152.2+26.2
malilib_version=0.29.0
tweakeroo_version=0.29.0
litematica_version=0.28.0
mod_menu_version = 20.0.0-beta.3